cd build/
./test_general_graph_optimizor_polynomial_problem
./test_general_graph_optimizor_marginalization
./test_kalman_filter_constant
./test_kalman_filter_imu_attitude ../examples/imu_pose_noise.txt
./test_general_graph_optimizor_pos_norm_plane_BA
./test_general_graph_optimizor_pos_unit_sphere_BA
./test_general_graph_optimizor_invdep_norm_plane_BA
./test_general_graph_optimizor_invdep_unit_sphere_BA
cd ..